CREATE TABLE [dbo].[DISTRICTS](
	[DistrictID] [int] NOT NULL,
	[DistrictName] NVARCHAR(50) NULL,
	[City] NVARCHAR(50) NULL,
	[State] [nvarchar](50) NULL,
 CONSTRAINT [PK_PLANTILLA] PRIMARY KEY CLUSTERED 
(
	[DistrictID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]