CREATE TABLE [dbo].[DOCTORS](
	[DoctorID] [int] NOT NULL,
	[DoctorLastName] NVARCHAR(50) NULL,
	[Speciality] [nvarchar](50) NULL,
	[DoctorSalary] MONEY NULL,
	[HospitalID] INT NULL
 CONSTRAINT [PK_DOCTOR] PRIMARY KEY CLUSTERED 
(
	[DoctorID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]