CREATE TABLE [dbo].[DEPARTMENTS](
	[DeptID] [int] NOT NULL,
	[DeptName] [nvarchar](50) NOT NULL,
	[DeptLocation] [nvarchar](50) NULL,
 CONSTRAINT [PK_DEPT] PRIMARY KEY CLUSTERED 
(
	[DeptID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]